### ISSUE TITLE
The effect of skip connection from Transition Block 1

### ISSUE THREAD

**Issue by iumyx2612** [yan-hao-tian/VW#10]
"The output of LawinASPP is upsampled to the size of a quarter of input image, **then fused with the first-level feature by a linear layer**".  
I see this gives a 0.8% performance gain in Table 6. The only explanation you gave is "which manifests the importance of low-level information" in Section 4.3.3. Is that all, are there anymore intuitions or proof?

**Comment by yan-hao-tian** [comment]
The feature input to the lawin decoder only uses three-level feature-maps, discarding the first-level feature in terms of efficiency. However, most existing semseg methods driven by vision transformers aggregate four-level feature-maps of the backbone(because vision transformers cannot vary the output stride of feature flexibly like CNN). So, the very basic intuition to fuse the output with the first-level feature is using all-level feature-maps just like other papers working on segmentation transformers.

Actually, deeplabv3+ also used a similar structure, which enhances the output of the decoder with the first-level feature-map but not by a linear layer.

IMO, the U-shape structure semseg network(U-Net, LinkNet) can be deemed as a prototype of such methodologies.

**Comment by iumyx2612** [comment]
> The feature input to the lawin decoder only uses three-level feature-maps, discarding the first-level feature in terms of efficiency. However, most existing semseg methods driven by vision transformers aggregate four-level feature-maps of the backbone(because vision transformers cannot vary the output stride of feature flexibly like CNN). So, the very basic intuition to fuse the output with the first-level feature is using all-level feature-maps just like other papers working on segmentation transformers.
> 
> Actually, deeplabv3+ also used a similar structure, which enhances the output of the decoder with the first-level feature-map but not by a linear layer.
> 
> IMO, the U-shape structure semseg network(U-Net, LinkNet) can be deemed as a prototype of such methodologies.

Oh I didn't pay attention that Lawin only aggregates last 3-level feature maps. If Lawin aggregate all 4-level, is the skip connection from the highest resolution feature maps from backbone still beneficial (I modified Lawin architecture a little bit below)? I was working on a similar arch like this, and the skip connection even after aggregating all 4-level still brings a good amount of performance boost.
![image](https://user-images.githubusercontent.com/69593462/188482085-b9ef7f30-9051-47c1-885d-a6da9d260c75.png)

**Comment by yan-hao-tian** [comment]
> If Lawin aggregate all 4-level, is the skip connection from the highest resolution feature maps from backbone still beneficial

I think so. It's reasonable.

**Comment by iumyx2612** [comment]
> > If Lawin aggregate all 4-level, is the skip connection from the highest resolution feature maps from backbone still beneficial
> 
> I think so. It's reasonable.

Thank you!
